query allPublishedRoasters {
  allPublishedRoasters {
    id
    name
    address
    image
    published
    beans {
      name
      process
      reviews {
        content
        author {
          id
          name
        }
      }
    }
  }
}