query beanById($id: String!) {
  beanById(id: $id) {
    id
    name
    images
    description
    published
    process
    origin
    tastingNotes
    website
    roaster {
      id
      name
    }
    reviews {
      id
      content
      author {
        name
        avatar
      }
    }
  }
}
