query roasterById($id: String!) {
  roasterById(id: $id) {
    id
    name
    description
    address
    country
    website
    image
    published
    beans {
      id
      name
      image
      description
    }
  }
}
